const products = [
  {
    id: 1,
    name: "Tops and skirt set for Female",
    category: "womans",
    brand: "richman",
    price: 19.0,
    originalPrice: 21.0,
    quantity: 30,
    rating: 4.9,
    reviews: 16,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/01.webp",
  },
  {
    id: 2,
    name: "Leather belt steve madden men's",
    category: "mans",
    brand: "lubana",
    price: 14.0,
    originalPrice: null,
    quantity: 23,
    rating: 4.5,
    reviews: 38,
    sold: 189,
    revenue: "$9k",
    image: "https://mironcoder-hotash.netlify.app/images/product/02.webp",
  },
  {
    id: 3,
    name: "Existing product name 3",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: 44.0,
    quantity: 30,
    rating: 4.1,
    reviews: 69,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/03.webp",
  },
  {
    id: 4,
    name: "Existing product name 4",
    category: "kidz",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: null,
    quantity: 30,
    rating: 4.4,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/04.webp",
  },
  {
    id: 5,
    name: "Existing product name 5",
    category: "accessory",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: null,
    quantity: 30,
    rating: 5.0,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/05.webp",
  },
  {
    id: 6,
    name: "Existing product name 6",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: null,
    quantity: 30,
    rating: 3.7,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/06.webp",
  },
  {
    id: 7,
    name: "Existing product name 7",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: 44.0,
    quantity: 30,
    rating: 4.5,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/07.webp",
  },
  {
    id: 8,
    name: "Existing product name 8",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: null,
    quantity: 30,
    rating: 4.3,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/08.webp",
  },
  {
    id: 9,
    name: "Existing product name 9",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: 44.0,
    quantity: 30,
    rating: 4.8,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/09.webp",
  },
  {
    id: 10,
    name: "Existing product name 10",
    category: "womans",
    brand: "ecstasy",
    price: 33.0,
    originalPrice: null,
    quantity: 30,
    rating: 3.9,
    reviews: 47,
    sold: 380,
    revenue: "$38k",
    image: "https://mironcoder-hotash.netlify.app/images/product/10.webp",
  },
];

export {products};